N = lambda x, y, w, title, sub='', icon='server', tone='blue', **k: dict(x=x, y=y, w=w, title=title, sub=sub, icon=icon, tone=tone, **k)

DIAGRAM = dict(w=1120, h=470,
  zones=[
    dict(x=20, y=20, w=225, h=440, title='Where invoices arrive', kind='ext'),
    dict(x=270, y=20, w=570, h=440, title='Agent platform, in your data centre', kind='ai'),
    dict(x=865, y=20, w=235, h=300, title='Enterprise systems', kind='ent'),
    dict(x=865, y=340, w=235, h=120, title='People', kind='sec'),
  ],
  nodes={
    'mail': N(35, 60, 195, 'AP mailbox', 'PDF and image invoices', 'mail', 'slate'),
    'portal': N(35, 150, 195, 'Supplier portal', 'uploads and e-invoices', 'globe', 'slate'),
    'scan': N(35, 240, 195, 'Scanned paper', 'plant offices, 6 sites', 'scan', 'slate'),
    'edi': N(35, 330, 195, 'GST e-invoice data', 'IRN and QR checks', 'doc', 'slate'),
    'intake': N(290, 60, 258, 'Intake and extraction', 'OCR, layout, field capture', 'scan', 'violet'),
    'guard': N(565, 60, 258, 'Guardrails and policy', 'limits, PII masking, allow-list', 'shield', 'pink'),
    'orch': N(290, 150, 258, 'AP agent (orchestrator)', 'plans steps, calls tools', 'robot', 'violet'),
    'llm': N(565, 150, 258, 'Self-hosted LLM', '30B-class model, 4 GPUs', 'llm', 'violet'),
    'tools': N(290, 240, 258, 'Tool gateway (MCP)', 'only approved actions', 'flow', 'blue'),
    'index': N(565, 240, 258, 'Contract and PO index', 'search over terms, rates', 'search', 'blue'),
    'audit': N(290, 360, 258, 'Audit trail', 'every step, every decision', 'lock', 'slate'),
    'eval': N(565, 360, 258, 'Quality monitoring', 'sampled checks, drift alerts', 'chart', 'slate'),
    'erp': N(880, 60, 205, 'ERP finance', 'PO, GRN, posting', 'grid', 'green'),
    'vm': N(880, 150, 205, 'Vendor master', 'bank, GSTIN, terms', 'building', 'green'),
    'pay': N(880, 240, 205, 'Payment run', 'weekly, with discounts', 'money', 'green'),
    'ap': N(880, 380, 205, 'AP team approvals', 'exceptions only', 'person', 'pink'),
  },
  flows=[
    dict(a='mail', b='intake', kind='data', n=1),
    dict(a='portal', b='intake', kind='data', via=[(258, 179), (258, 89)]),
    dict(a='scan', b='intake', kind='data', via=[(258, 269), (258, 89)]),
    dict(a='edi', b='intake', kind='data', via=[(258, 359), (258, 89)]),
    dict(a='intake', b='orch', kind='data', n=2, label='fields + confidence'),
    dict(a='orch', b='llm', kind='control', n=3, both=True),
    dict(a='llm', b='guard', kind='control', label='every prompt checked'),
    dict(a='orch', b='tools', kind='control', n=4, label='tool calls'),
    dict(a='tools', b='index', kind='control'),
    dict(a='tools', b='erp', kind='control', n=5, label='match and post', sa=('b', 100), via=[(519, 330), (851, 330), (851, 89)], lpos=(700, 330)),
    dict(a='tools', b='vm', kind='control', sa=('b', 100), via=[(519, 330), (851, 330), (851, 179)]),
    dict(a='tools', b='pay', kind='control', sa=('b', 100), via=[(519, 330), (851, 330), (851, 269)]),
    dict(a='tools', b='ap', kind='alert', n=6, sa=('b', 100), via=[(519, 330), (851, 330), (851, 409)], lpos=(851, 372)),
    dict(a='tools', b='audit', kind='mgmt', sa=('b', -60), sb=('t', -60), label='logged', lpos=(359, 330)),
    dict(a='audit', b='eval', kind='mgmt'),
  ])

S = dict(
  slug='agentic-ai-accounts-payable',
  short='Agentic AI for accounts payable',
  eyebrow='Agentic AI',
  card='An AI agent reads, checks and posts supplier invoices for a manufacturing group, with people approving every exception.',
  topic='agents',
  title='Agentic AI for accounts payable | Reference deployment | Vakratron',
  desc='How a manufacturing group uses a self-hosted AI agent to read, match and post 40,000 supplier invoices a month, with guardrails, a tool gateway, human approval for exceptions and a full audit trail.',
  h1='An AI agent that clears supplier invoices, and knows when to ask a person',
  lead='A manufacturing group with six plants receives about 40,000 supplier invoices a month in every format imaginable. Twenty-two people spend most of their day typing them into the ERP. This design puts an AI agent in front of that work: it reads, checks and posts the routine invoices, and hands anything unusual to a person with the reasons laid out.',
  facts=[('Sector', 'Manufacturing'), ('Volume', '~40,000 invoices/month'), ('Programme', '16 weeks to scale'), ('Model', 'Self-hosted, on-premises')],
  situation_h2='Skilled people doing data entry, and still paying late',
  situation=[
    'Invoices arrive by email, through a supplier portal and on paper at plant offices. About 3,000 active suppliers use their own layouts. The accounts payable team keys each one into the ERP, then matches it against the purchase order and the goods receipt before it can be paid.',
    'On average an invoice takes nine days from arrival to posting. At month end the backlog doubles. Early-payment discounts are missed, suppliers chase payment by phone, and an internal audit found duplicate payments in about 0.4% of a sample.',
    'The finance director had seen generic invoice-scanning tools fail on the variety of layouts. The question was whether an agent that can reason about an invoice, look things up and follow the company&rsquo;s own rules could do better, without sending pricing data outside the company.',
  ],
  constraints=[
    'Invoice and pricing data must not leave the company. No public AI APIs.',
    'The ERP stays the system of record. The agent cannot post anything the rules do not allow.',
    'Every action must be explainable to statutory auditors months later.',
    'Payments above set limits, new suppliers and bank-detail changes always need a person.',
    'GST checks on every invoice: valid GSTIN, IRN for e-invoices, correct tax split.',
  ],
  options_h2='Why an agent, and not just better OCR',
  options_intro='Three approaches were compared on a sample of 2,000 historical invoices, scored on correct postings and on how many still needed a person.',
  options=[
    ['Template OCR plus RPA', 'Cheap and familiar. Works well on the top 50 suppliers.', 'A template per layout. Breaks when a supplier changes format. Cannot reason about a mismatch.', 'Rejected'],
    ['SaaS AP automation', 'Fast to start, good extraction.', 'Invoice data leaves the company. ERP integration and per-invoice fees add up at this volume.', 'Rejected'],
    ['Self-hosted agent with tool gateway', 'Reads any layout, reasons about mismatches, follows company rules, data stays inside.', 'Needs GPU capacity, an evaluation routine and careful tool design.', '<span class="pick">Chosen</span>'],
  ],
  arch_h2='The agent can only do what the tool gateway allows',
  arch_intro='The language model never talks to the ERP directly. The agent plans each step, but every action goes through a tool gateway that exposes a small set of approved operations, each with its own limits. Guardrails check every prompt and answer, and every step lands in an audit trail.',
  arch_caption='Numbered flows: (1) an invoice arrives from any channel, (2) fields are extracted with a confidence score, (3) the agent reasons with the self-hosted model, (4) it calls approved tools, (5) the gateway matches against the PO and goods receipt and posts, (6) anything outside the rules goes to a person.',
  diagram=DIAGRAM,
  parts=[
    ('Intake and extraction', 'OCR and layout analysis turn any PDF, image or e-invoice into fields with a confidence score for each one. Low-confidence fields are flagged, not guessed.'),
    ('AP agent', 'Plans the steps for each invoice: identify the supplier, find the PO, check quantities and prices, check tax, then decide to post or escalate. It writes down its reasoning for every decision.'),
    ('Self-hosted LLM', 'A 30B-class open model on four GPUs in the company&rsquo;s own data centre, served with batching. A smaller model handles simple, well-known suppliers.'),
    ('Tool gateway (MCP)', 'The only way the agent touches business systems. It exposes about a dozen operations such as &ldquo;find PO&rdquo;, &ldquo;check goods receipt&rdquo; and &ldquo;post invoice under limit&rdquo;, each with value limits, rate limits and its own service account.'),
    ('Guardrails and policy', 'Masks bank details and personal data in prompts, strips instructions hidden inside invoice text, and enforces the allow-list of tools.'),
    ('Contract and PO index', 'A searchable store of purchase orders, contract rates and payment terms, so the agent can check a price against what was agreed.'),
    ('Human approval queue', 'Exceptions arrive with the invoice, the extracted fields, what did not match and a suggested action. One click to approve, edit or reject.'),
    ('Audit trail and quality monitoring', 'Every input, tool call and decision is stored. A weekly sample is re-checked by the AP team and scored, and drift raises an alert.'),
  ],
  sizing_h2='GPU capacity sized from invoice volume and month-end peaks',
  sizing_intro='Volume is about 1,800 invoices on a normal working day and about 5,500 on the busiest month-end day. Each invoice needs on average six model calls.',
  sizing_head=['Item', 'Figure', 'Basis'],
  sizing=[
    ['Peak daily invoices', '~5,500', 'Month end, 3x a normal day'],
    ['Model calls per invoice', '~6', 'Extraction check, matching, tax, decision, summary'],
    ['Peak model calls', '~33,000 a day, about 1 per second over 10 hours', 'Comfortable for one replica, two for availability'],
    ['Tokens per call', '~3,000 in, ~400 out', 'Invoice text plus PO lines and rules'],
    ['GPUs', '4 x 48 GB (2 replicas x 2 GPUs)', '30B-class model at 8-bit, batching enabled'],
    ['Simple-invoice route', 'Small model on 1 GPU', 'Handles about 40% of volume from known suppliers'],
    ['Storage', '~6 TB a year', 'Invoice images, extracted data and audit trail, kept 8 years'],
  ],
  sizing_note='Before buying GPUs, the same workload is benchmarked on a short-term rented server with the chosen model, so the hardware order is based on measured throughput.',
  delivery_h2='From shadow mode to straight-through, in four steps',
  delivery_intro='The agent earns trust gradually. It starts by watching, then suggesting, and only then posting, and only within limits.',
  phases=[
    ('Baseline', 'Weeks 1 to 3', '2,000 historical invoices labelled with the right answer. Tool gateway built against an ERP test system.', 'Field accuracy measured on the labelled set.'),
    ('Shadow mode', 'Weeks 4 to 7', 'The agent processes live invoices in parallel but posts nothing. Its decisions are compared with the team&rsquo;s.', '98.5% field accuracy, zero wrong supplier matches.'),
    ('Assisted', 'Weeks 8 to 11', 'The agent prepares every posting and a person clicks approve. Approval time and edits are measured.', 'Fewer than 5% of suggestions edited.'),
    ('Straight-through', 'Weeks 12 to 16', 'Routine PO-matched invoices under the limit post automatically. Everything else goes to people.', 'Monthly audit sample clean for two months.'),
  ],
  rollback='Straight-through posting is a switch per supplier group and per value band. It can be turned off in seconds, and the team is back in assisted mode with nothing lost.',
  risks_h2='The risks that matter with an agent, and how each is contained',
  risks=[
    ['Wrong values', 'The model misreads an amount or invents a field', 'Every value is checked against the PO, the goods receipt and GST data. Mismatches go to a person, never to posting.'],
    ['Instructions hidden in invoices', 'Text in an invoice tries to change the agent&rsquo;s behaviour', 'Invoice content is treated as data only. Guardrails strip instructions, and the tool allow-list means there is nothing dangerous to call.'],
    ['Bank-detail fraud', 'A fake invoice carries new bank details', 'The agent can never change vendor bank details. Any mismatch with the vendor master is an automatic exception.'],
    ['Model drift', 'Accuracy slips as suppliers change layouts', 'Weekly sampled checks, alerts on falling confidence, and re-evaluation before any model update.'],
    ['ERP outage', 'Postings fail part-way', 'The gateway queues operations and retries safely. Each posting has an idempotency key, so nothing posts twice.'],
  ],
  opt_h2='What was optimised',
  optimised=[
    ('40%', 'Routed to a small model', 'Known suppliers with clean layouts go to a small, fast model. The large model handles the hard cases.'),
    ('4 GPUs', 'Right-sized serving', 'Batching and quantisation fit peak volume on four GPUs instead of eight.'),
    ('12', 'Tools, not free access', 'A dozen narrow operations are easier to test, audit and secure than broad ERP access.'),
    ('1 click', 'Faster human review', 'Exceptions arrive with the reason and a suggested action, so a person decides in seconds.'),
    ('0', 'Data sent outside', 'Model, index and logs all run on the company&rsquo;s own hardware.'),
    ('Weekly', 'Measured quality', 'Accuracy is a number on a dashboard, not an impression.'),
  ],
  outcomes_h2='What the design is built to deliver',
  outcomes=[
    ['Invoices posted without manual keying', '0%', '60 to 70% of PO-backed invoices'],
    ['Arrival to posting', '~9 days', 'Under 2 days, same day for straight-through'],
    ['AP effort on data entry', 'Most of the day', 'Down about 70%; the team moves to exceptions and supplier queries'],
    ['Duplicate payments', '~0.4% in audit sample', 'Caught before posting'],
    ['Early-payment discounts', 'Often missed', 'Captured when terms allow'],
    ['Audit evidence', 'Manual sampling', 'Full trail for every invoice'],
  ],
  outcomes_note='Targets are confirmed in the baseline and shadow phases on your own invoices. Straight-through rates depend heavily on how many invoices have a clean PO and goods receipt.',
  skills=[
    ('Agent design', 'Breaking a business process into steps, tools and decision points an agent can follow safely.'),
    ('Tool gateway and MCP', 'Narrow, testable operations with limits, service accounts and idempotent retries.'),
    ('LLM serving on GPUs', 'Model selection, quantisation, batching and capacity planning from real volumes.'),
    ('Document AI', 'OCR and layout extraction across thousands of supplier formats, with confidence scoring.'),
    ('AI security', 'Prompt-injection defences, PII masking and allow-lists that hold up in an audit.'),
    ('ERP integration', 'Three-way matching, posting rules and safe integration with finance systems.'),
  ],
  cta_h2='Have a process where people spend the day copying data between systems?',
  cta_p='Tell us the process, the volumes and the systems involved. We will come back with a plain view of what an agent could safely take on, what should stay with people, and how to prove it before going live.',
)
