N = lambda x, y, w, title, sub='', icon='server', tone='blue', **k: dict(x=x, y=y, w=w, title=title, sub=sub, icon=icon, tone=tone, **k)

DIAGRAM = dict(w=1120, h=600,
  zones=[
    dict(x=20, y=20, w=1080, h=100, title='Internet and customers', kind='ext'),
    dict(x=20, y=150, w=300, h=440, title='Public cloud (kept)', kind='cloud', dashed=True),
    dict(x=350, y=150, w=520, h=440, title='Private cloud, colocation DC 1', kind='dc'),
    dict(x=895, y=150, w=205, h=440, title='DC 2: recovery', kind='dr'),
  ],
  nodes={
    'users': N(60, 52, 210, 'Customer users', '1,200 companies, HR + payroll', 'users', 'slate'),
    'cdn': N(455, 52, 230, 'CDN and WAF', 'TLS, bot and DDoS filtering', 'shield', 'pink'),
    'partner': N(860, 52, 220, 'Partner APIs', 'banks, tax, attendance', 'link', 'slate'),
    'burst': N(40, 190, 260, 'Burst node pool', 'scales out for tax season', 'k8s', 'amber'),
    'exit': N(40, 350, 260, 'Exit estate', '260 VMs + managed SQL', 'vm', 'amber', state='off', tag='MOVING'),
    'arch': N(40, 430, 260, 'Cold archive tier', '7-year payroll records', 'archive', 'amber'),
    'lb': N(370, 190, 235, 'Load balancers', 'HA pair, L4 + L7', 'lb', 'blue'),
    'fw': N(620, 190, 235, 'Edge firewalls', 'active-standby pair', 'firewall', 'pink'),
    'k8sp': N(370, 270, 235, 'Kubernetes: production', '3 masters, 40 workers', 'k8s', 'blue'),
    'k8sn': N(620, 270, 235, 'Kubernetes: non-prod', 'dev, QA, staging', 'k8s', 'slate'),
    'pg': N(370, 350, 235, 'PostgreSQL HA', 'Patroni, 3 nodes, NVMe', 'storage', 'green'),
    'cmp': N(620, 350, 235, 'OpenStack + KVM', '24 hosts, ~4,600 vCPU', 'server', 'blue'),
    'obs': N(370, 430, 235, 'Observability', 'metrics, logs, traces', 'chart', 'slate'),
    'ceph': N(620, 430, 235, 'Ceph block + object', '10 nodes, ~920 TB raw', 'storage', 'green'),
    'fab': N(370, 515, 485, 'Spine-leaf network fabric', '2 x 100G spine, 25G to every host', 'switch', 'slate'),
    'dbs': N(910, 200, 178, 'DB standby', 'async, ~5 min lag', 'storage', 'violet'),
    'bk': N(910, 300, 178, 'Immutable backup', 'object lock, 35 days', 'lock', 'violet'),
    'rb': N(910, 400, 178, 'Recovery runbooks', 'rebuild in 1 hour', 'doc', 'violet'),
  },
  flows=[
    dict(a='users', b='cdn', kind='traffic', label='HTTPS'),
    dict(a='cdn', b='fw', kind='traffic', sa=('b', 50), sb='t'),
    dict(a='fw', b='lb', kind='traffic'),
    dict(a='lb', b='k8sp', kind='traffic'),
    dict(a='partner', b='fw', kind='traffic', sa='b', sb=('t', 60), via=[(970, 135), (797, 135)]),
    dict(a='k8sp', b='pg', kind='data', label='SQL'),
    dict(a='cmp', b='ceph', kind='data', label='volumes'),
    dict(a='burst', b='k8sp', kind='control', label='10G link', lpos=(332, 259), via=[(332, 219), (332, 299)]),
    dict(a='exit', b='pg', kind='data', n=1, label='wave replication', lpos=(334, 340)),
    dict(a='pg', b='dbs', kind='data', n=2, label='replica', sa=('t', 70), via=[(557, 339), (878, 339), (878, 229)], lpos=(760, 339)),
    dict(a='ceph', b='bk', kind='batch', n=3, label='nightly', via=[(892, 459), (892, 329)], lpos=(892, 400)),
    dict(a='ceph', b='arch', kind='batch', sa='b', sb='b', via=[(737, 500), (170, 500)], label='tiering after 13 months', lpos=(255, 500)),
  ])

S = dict(
  slug='public-to-private-cloud',
  short='Public cloud to private cloud',
  eyebrow='Cloud repatriation',
  card='A B2B SaaS company moves its steady workloads off public cloud to a private cloud, and keeps burst capacity where it is cheap.',
  topic='cloud',
  title='Public cloud to private cloud repatriation | Reference deployment | Vakratron',
  desc='How a B2B SaaS company moves steady-state workloads from Azure to an OpenStack private cloud in colocation, keeps burst on public cloud, and cuts run cost without customer downtime.',
  h1='Moving a SaaS platform from public cloud to its own private cloud',
  lead='A payroll and HR software company had grown up on Azure. Six years later the bill had tripled, most of it for workloads that never changed size. This is how the move to a private cloud is designed so customers notice nothing except faster pages, and the company keeps the public cloud for the few things it is genuinely good at.',
  facts=[('Sector', 'B2B SaaS'), ('Estate', '260 VMs, 2 AKS clusters'), ('Programme', '7 months, 5 waves'), ('Model', 'Hybrid: private + burst')],
  situation_h2='A cloud bill that grew faster than the business',
  situation=[
    'The company runs payroll and HR software for about 1,200 mid-size and large employers in India. Everything lives on Azure: around 260 virtual machines, two Kubernetes clusters, managed PostgreSQL and SQL, and about 180 TB of documents in Blob storage.',
    'Monthly spend had climbed from roughly ₹40 lakh to ₹1.4 crore in three years. When the finance team broke it down, about 80% of the cost came from workloads that run at the same size all year: the core application, databases and document store. Data leaving the cloud to customers, around 60 TB a month, had become a line item on its own.',
    'At the same time, larger customers, including two banks, were asking harder questions in audits about where payroll data physically sits and who can reach it. The board asked a simple question: is there a cheaper way to run the same thing, without risking a single payroll run?',
  ],
  constraints=[
    'No payroll run can be put at risk. Nothing moves between the 25th and the 5th of any month.',
    'No customer-visible downtime longer than 30 minutes for any service, with a tested way back.',
    'ISO 27001 and SOC 2 controls must stay intact through the move, with evidence for auditors.',
    'A platform team of nine engineers who know Azure well, but have not run OpenStack or Ceph.',
    'Tax season brings a 3x peak for about six weeks a year. That capacity cannot sit idle all year.',
  ],
  options_h2='Four ways forward, compared honestly',
  options_intro='Repatriation is not automatically the right answer. Each option was costed over five years on the same workload data.',
  options=[
    ['Stay and optimise', 'Reserved instances and rightsizing cut 25 to 30%. No migration risk.', 'Egress and managed-service premiums remain. Savings plateau after year one.', 'Do first, regardless'],
    ['Move to another public cloud', 'Possible discounts in year one.', 'Same cost structure, a full migration for a one-off saving.', 'Rejected'],
    ['Full repatriation', 'Lowest steady-state cost.', 'Tax-season peak needs 3x hardware sitting idle 46 weeks a year.', 'Rejected'],
    ['Hybrid: steady state private, burst and archive on public', 'Lowest five-year cost with peak covered. Data location becomes simple to evidence.', 'Two environments to run, so tooling must be shared from day one.', '<span class="pick">Chosen</span>'],
  ],
  arch_h2='Private cloud for the steady 80%, public cloud for the peaks',
  arch_intro='Production runs in a colocation data centre on an open-source stack. A second site holds the database replica, immutable backups and everything needed to rebuild. Azure stays connected through a private link for burst capacity and cold archive.',
  arch_caption='Numbered flows: (1) workloads move wave by wave while data replicates from the old estate, (2) database replica to the recovery site, (3) nightly immutable backups. Burst traffic uses the private interconnect, never the internet.',
  diagram=DIAGRAM,
  parts=[
    ('Edge firewalls and load balancers', 'One controlled entry point for customers and partners. Behind the same CDN and WAF the company already uses, so DNS cut-over is just a change of origin.'),
    ('Kubernetes on OpenStack', 'Production and non-production clusters on KVM virtual machines. Same container images and Helm charts as on Azure, so applications do not change.'),
    ('PostgreSQL with Patroni', 'Three-node HA cluster on local NVMe replaces the managed database. Automatic failover inside the site, asynchronous replica in the second site.'),
    ('Ceph block and object storage', 'Volumes for VMs and containers, and an S3-compatible store for 180 TB of payslips and documents. Erasure coding keeps the object tier efficient.'),
    ('Spine-leaf fabric', 'Two 100G spines and 25G to every host. Storage and application traffic on separate VLANs so a rebuild never slows payroll.'),
    ('Burst pool and archive on Azure', 'An AKS node pool that scales out only in tax season, reached over a 2 x 10G private interconnect. Records older than 13 months tier to Azure cold archive.'),
    ('Recovery site', 'Database replica, immutable backups with 35-day object lock, and runbooks to rebuild the platform from code. Tested every quarter.'),
  ],
  sizing_h2='From 90 days of real usage, not from the current VM list',
  sizing_intro='Azure VMs averaged 22% CPU use across the estate. Sizing used the 95th percentile of 90 days of metrics, then added headroom for two years of growth and one host failure per rack.',
  sizing_head=['Resource', 'Used today (p95)', 'Private cloud design', 'How it was arrived at'],
  sizing=[
    ['vCPU', '~2,300 in use (of 6,800 provisioned)', '24 hosts, 2 x 48 cores each, ~4,600 vCPU at 2:1', 'p95 use, +40% growth, N+2 hosts'],
    ['Memory', '~9 TB in use', '24 x 768 GB = 18 TB', 'Memory is not overcommitted'],
    ['Block storage', '~120 TB', '3-way replicated on NVMe', 'Databases and volumes'],
    ['Object storage', '~180 TB, growing 4 TB/month', 'Erasure coded 4+2', '10 Ceph nodes, ~920 TB raw, ~60% used at go-live'],
    ['Network', '60 TB/month egress', '2 x 10G IP transit, flat rate', 'Peak 3.2 Gbps measured'],
    ['Burst', '3x peak for 6 weeks', 'AKS node pool, 0 to 30 nodes', 'Pay only for the weeks used'],
  ],
  sizing_note='Hardware is sized for two years. A third rack position is reserved in the colocation contract so year-three growth is a purchase order, not a redesign.',
  delivery_h2='Five waves, each one reversible',
  delivery_intro='Every wave runs in both places for two weeks before Azure is switched off. Nothing moves in the payroll window.',
  phases=[
    ('Discover and order', 'Weeks 1 to 4', 'Dependency map of all 260 VMs and 140 services, from traffic data. Hardware ordered in week 2 to cover lead times.', 'Every service has an owner, a wave and a rollback plan.'),
    ('Build the platform', 'Weeks 5 to 14', 'Racks, fabric, OpenStack, Ceph and Kubernetes built from code. Monitoring and backup working before any workload lands.', 'Failure tests passed: host, switch, disk and site link.'),
    ('Non-production first', 'Weeks 15 to 18', 'Dev, QA and staging move. The platform team runs it daily and fixes what is awkward.', 'Two weeks of normal development with no platform tickets open.'),
    ('Production waves', 'Weeks 19 to 28', 'Four waves, smallest risk first. Databases replicate ahead of each wave, DNS weights shift 10%, 50%, 100%.', 'Error rate and latency equal or better for 14 days.'),
    ('Decommission', 'Weeks 29 to 30', 'Azure resources removed except burst pool and archive. Contracts and reservations closed.', 'Bill reconciled, audit evidence pack signed off.'),
  ],
  rollback='During each wave, traffic weights can move back to Azure in minutes and the database replicates in both directions until sign-off. No wave closes until its rollback has been rehearsed.',
  risks_h2='What could go wrong, and what is already in the plan',
  risks=[
    ['Team skills', 'Nine engineers inherit OpenStack and Ceph overnight', 'Hands-on training from week 5, runbooks written with the team, and six months of co-run support after go-live.'],
    ['Hidden managed-service dependencies', 'An application quietly relies on an Azure-only service', 'Found in discovery from traffic and code scans. Service Bus and Key Vault mapped to RabbitMQ and Vault before wave 1.'],
    ['Hardware lead time', 'Servers or switches arrive late and push the programme into payroll', 'Ordered in week 2 with dates in the contract. Waves are planned around freeze windows with slack.'],
    ['Database cut-over', 'Data lost or out of sync at switch-over', 'Logical replication for days ahead of each wave, checksums compared, cut-over rehearsed twice on a copy.'],
    ['Single colocation site', 'Facility issue takes the platform down', 'Second site holds a replica and backups. Rebuild runbook tested every quarter with a measured time.'],
  ],
  opt_h2='Where the savings actually come from',
  optimised=[
    ('2:1', 'Right-sized compute', 'Sized from real p95 usage, not from 6,800 provisioned vCPU. Overcommit only on CPU, never on memory.'),
    ('1.5x', 'Efficient object storage', 'Erasure coding 4+2 instead of three full copies for 180 TB of documents.'),
    ('Flat', 'Predictable egress', 'Customer downloads move from per-GB billing to flat-rate IP transit in the colocation facility.'),
    ('0', 'Licence lock-in', 'OpenStack, KVM, Ceph, Kubernetes and PostgreSQL are open source. Support is bought, not licences per core.'),
    ('6 weeks', 'Peak paid only when used', 'Tax-season capacity stays on public cloud and scales to zero afterwards.'),
    ('1 codebase', 'Same tooling both sides', 'Terraform, Helm and one monitoring stack cover private and public, so the team does not run two worlds.'),
  ],
  outcomes_h2='What the design is built to deliver',
  outcomes=[
    ['Monthly run cost', '~₹1.4 crore', '45 to 55% lower from year two, including hardware over five years, colocation and support'],
    ['Payback on hardware', '-', '14 to 18 months'],
    ['Egress cost', '60 TB/month at per-GB rates', 'Fixed, inside the IP transit contract'],
    ['Page load for Indian users (p95)', '~620 ms', 'Under 400 ms, with the platform closer to users'],
    ['Recovery', 'Depends on cloud region', 'RPO about 5 minutes, RTO 1 hour, tested quarterly'],
    ['Data location evidence', 'Shared responsibility documents', 'Own racks, own access logs, one audit pack'],
  ],
  outcomes_note='Targets are set during design and measured after each wave. Cost figures depend on hardware pricing, colocation rates and growth, and are re-run with your own data during assessment.',
  skills=[
    ('FinOps and cost modelling', 'Five-year cost models that compare options on the same usage data, including people and support.'),
    ('OpenStack and KVM', 'Private cloud design, high availability for the control plane, and day-2 upgrades.'),
    ('Ceph storage', 'Block and object design, erasure coding, failure domains and rebuild behaviour.'),
    ('Kubernetes platforms', 'Cluster design, GitOps delivery and running the same workloads across private and public.'),
    ('Database migration', 'PostgreSQL HA, logical replication and rehearsed cut-overs with checksums.'),
    ('Migration programme design', 'Dependency mapping, wave planning around business calendars, and rollback at every step.'),
  ],
  cta_h2='Wondering if your cloud bill would look different on your own platform?',
  cta_p='Send us a cost export and a rough list of what runs where. We will come back with a plain first view: which workloads are worth moving, which should stay, and what the five-year numbers look like.',
)
